# Generated by Django 2.0.1 on 2018-10-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_right', models.CharField(help_text='Enter the Total no of Right Answers ', max_length=20, verbose_name='Answer Right')),
                ('avg_time', models.CharField(help_text='Enter the Average Time for Solve the Exam', max_length=20, verbose_name='Avg Time')),
                ('avg_clicks', models.CharField(help_text='Enter the Average Clicks', max_length=20, verbose_name='Avg Clicks')),
                ('avg_marked', models.CharField(help_text='Enter the Average no of questions marked for review', max_length=20, verbose_name='Avg Marked')),
                ('stu_class', models.CharField(help_text='Enter the Classification of Student', max_length=20, verbose_name='Answer')),
            ],
        ),
    ]
