# Generated by Django 2.0.1 on 2018-10-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_app', '0002_answer_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_details',
            name='ans_right',
            field=models.CharField(help_text='Enter the Total no of Right Answers ', max_length=20, verbose_name='Total no of Answers Right'),
        ),
        migrations.AlterField(
            model_name='answer_details',
            name='stu_class',
            field=models.CharField(help_text='Enter the Classification of Student', max_length=20, verbose_name='Classification'),
        ),
    ]
