# Generated by Django 2.0.1 on 2018-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_app', '0003_auto_20181006_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_details',
            name='stu_class',
            field=models.CharField(blank=True, help_text='Enter the Classification of Student', max_length=20, null=True, verbose_name='Classification'),
        ),
    ]
