# Generated by Django 2.0.1 on 2018-10-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_app', '0004_auto_20181006_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_details',
            name='choice_1',
            field=models.CharField(help_text='Enter the Answer Choice 1', max_length=500, verbose_name='Choice1'),
        ),
        migrations.AlterField(
            model_name='question_details',
            name='choice_2',
            field=models.CharField(help_text='Enter the Answer Choice 2', max_length=500, verbose_name='Choice2'),
        ),
        migrations.AlterField(
            model_name='question_details',
            name='choice_3',
            field=models.CharField(help_text='Enter the Answer Choice 3', max_length=500, verbose_name='Choice3'),
        ),
        migrations.AlterField(
            model_name='question_details',
            name='choice_4',
            field=models.CharField(help_text='Enter the Answer Choice 4', max_length=500, verbose_name='Choice4'),
        ),
        migrations.AlterField(
            model_name='question_details',
            name='question',
            field=models.CharField(help_text='Enter the Question', max_length=1000, verbose_name='Question'),
        ),
    ]
