# Generated by Django 2.0.1 on 2018-10-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_app', '0005_auto_20181006_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_details',
            name='avg_marked',
            field=models.CharField(help_text='Enter the Average no of questions marked for review', max_length=20, verbose_name='No of Questions Marked for Review'),
        ),
    ]
